from gnomad.resources.grch38 import (VersionedTableResource, TableResource)


from qc.constants import CURRENT_RELEASE, RELEASES

BUCKET = None


def get_sample_qc_root(version: str = CURRENT_RELEASE, mt: bool = False) -> str:
    """
    Return path to sample QC root folder
    :param bucket:  Root directory or bucket
    :param version: Version of sample QC path to return
    :param mt:      Whether path is for a MatrixTable, default is False
    :return:        Root to sample QC path
    """
    assert BUCKET
    return f"{BUCKET}/sample_qc/{'mt' if mt else 'ht'}/genomes_v{version}"


def get_sample_qc_url(strat: str = "all") -> VersionedTableResource:
    """
    Gets sample QC annotations generated by Hail for the specified stratification:
        - bi-allelic
        - multi-allelic
        - all
    :param bucket: Root directory or bucket
    :param strat:  Which stratification to return
    :return:       Sample QC table
    """
    return VersionedTableResource(
        CURRENT_RELEASE,
        {release: TableResource(f"{get_sample_qc_root(release)}/sample_qc_{strat}.ht")
                  for release in RELEASES})


# Sex imputation results
sex = VersionedTableResource(
    CURRENT_RELEASE,
    {release: TableResource(f"{get_sample_qc_root(release)}/sex.ht") for release in RELEASES}
)